name: aws-glue-dev

services:
  aws-glue-dev-container:
    container_name: aws-glue-dev
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    environment:
      AWS_PROFILE: aws-glue-dev
      DISABLE_SSL: true
      DATALAKE_FORMATS: hudi,delta,iceberg
    volumes:
      - type: bind
        source: ~/.aws
        target: /home/glue_user/.aws
        read_only: true
      - type: bind
        source: ./workspace
        target: /home/glue_user/workspace/jupyter_workspace
    ports:
      - 4040:4040 # Spark Web UI
      - 8888:8888 # JupyterLab
      - 8998:8998 # Apache Livy
      - 18080:18080 # Spark History Server
    command: /home/glue_user/jupyter/jupyter_start.sh
